#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const envPath = path.resolve(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
  console.error('No .env found; copy .env.example to .env and fill in your Spotify credentials.');
  process.exit(1);
}

const env = {};
for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
  const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+)\s*$/);
  if (m) env[m[1]] = m[2].replace(/^"|"$/g, '');
}

if (!env.SPOTIFY_CLIENT_ID || !env.SPOTIFY_CLIENT_SECRET || !env.SPOTIFY_OAUTH_CLIENT_ID) {
  console.error('SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, and SPOTIFY_OAUTH_CLIENT_ID must be set in .env');
  process.exit(1);
}

const PLACEHOLDERS = new Set([
  '',
  'your_client_id_here',
  'your_client_secret_here',
  'ci_placeholder_client_id',
  'ci_placeholder_client_secret',
  'your_oauth_client_id_here',
  'changeme',
  'TODO',
]);

if (
  PLACEHOLDERS.has(env.SPOTIFY_CLIENT_ID) ||
  PLACEHOLDERS.has(env.SPOTIFY_CLIENT_SECRET) ||
  PLACEHOLDERS.has(env.SPOTIFY_OAUTH_CLIENT_ID)
) {
  console.error('ERRO: .env contém credenciais placeholder ou vazias.');
  console.error('Configure SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET e SPOTIFY_OAUTH_CLIENT_ID com valores reais.');
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/embed-spotify.js. Do not commit.
module.exports = {
  clientId: ${JSON.stringify(env.SPOTIFY_CLIENT_ID)},
  clientSecret: ${JSON.stringify(env.SPOTIFY_CLIENT_SECRET)},
  oauthClientId: ${JSON.stringify(env.SPOTIFY_OAUTH_CLIENT_ID)},
  oauthRedirectUri: ${JSON.stringify(env.SPOTIFY_OAUTH_REDIRECT_URI || '')},
  oauthCallbackPort: ${JSON.stringify(env.SPOTIFY_OAUTH_CALLBACK_PORT || '5982')},
};
`;
fs.writeFileSync(path.resolve(__dirname, '..', 'main', 'spotify-creds.js'), out, 'utf8');
console.log('main/spotify-creds.js written.');
