#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const envPath = path.resolve(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
  console.error('No .env found; copy .env.example to .env and fill in your Spotify credentials.');
  process.exit(1);
}

const env = {};
for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
  const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+)\s*$/);
  if (m) env[m[1]] = m[2].replace(/^"|"$/g, '');
}

if (!env.SPOTIFY_CLIENT_ID || !env.SPOTIFY_CLIENT_SECRET) {
  console.error('SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET must be set in .env');
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/embed-spotify.js. Do not commit.
module.exports = {
  clientId: ${JSON.stringify(env.SPOTIFY_CLIENT_ID)},
  clientSecret: ${JSON.stringify(env.SPOTIFY_CLIENT_SECRET)},
};
`;
fs.writeFileSync(path.resolve(__dirname, '..', 'main', 'spotify-creds.js'), out, 'utf8');
console.log('main/spotify-creds.js written.');
